apiVersion: v2
name: promtail
description: Promtail is an agent which ships the contents of local logs to a Loki instance
type: application
appVersion: 3.5.1
version: 6.17.2
home: https://grafana.com/loki
sources:
  - https://github.com/grafana/loki
  - https://grafana.com/oss/loki/
  - https://grafana.com/docs/loki/latest/
icon: https://raw.githubusercontent.com/grafana/loki/master/docs/sources/logo.png

dependencies:
  - name: promtail
    version: 6.17.1
    repository: https://grafana.github.io/helm-charts