env: ~
region: ~
clusterName: in-cluster
project: infra
namespace: infra

prometheus:
  version: ~
  remoteWrite:
    url: ~
    secret:
      name: prometheus
      username: ~
      password: ~
  clusterName: ~

promtail:
  version: ~
  url: ~

argo-rollouts:
  version: ~
  values: ~

cluster-autoscaler:
  version: ~
  values: ~

ebs-csi-driver:
  version: ~
  values: ~

efs-csi-driver:
  version: ~
  values: ~

ingress-nginx:
  version: ~
  values: ~

metrics-server:
  version: ~
  values: ~
