{{- if .Values.app.secrets }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "name" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{ include "common-labels" . | nindent 4 }}
type: Opaque
stringData:
  {{- range $k, $v := .Values.app.secrets }}
  {{ $k }}: {{ $v | quote }}
  {{- end }}
{{- end }}
