apiVersion: v2
name: prometheus
version: 83.0.0
description: Prometheus is a monitoring system and time series database.
type: application

dependencies:
  - name: sealed-secret
    version: 0.1.*
    repository: https://moreirodamian.github.io/helm-charts/
  - name: kube-prometheus-stack
    version: 82.0.0
    repository: https://prometheus-community.github.io/helm-charts
  - name: prometheus-statsd-exporter
    version: 1.0.*
    repository: https://moreirodamian.github.io/helm-charts/