apiVersion: v2
name: prometheus-statsd-exporter
description: A Helm chart for prometheus stats-exporter
type: application
version: 1.0.1

dependencies:
  - name: prometheus-statsd-exporter
    version: 1.0.0
    repository: https://prometheus-community.github.io/helm-charts