apiVersion: v2
name: ingress-nginx
description: Ingress controller for Kubernetes using NGINX as a reverse proxy and load balancer
type: application
version: 5.0.0
dependencies:
  - name: ingress-nginx
    version: 4.14.3
    repository: https://kubernetes.github.io/ingress-nginx