apiVersion: v2
name: sealed-secrets
version: 2.18.2
description: Helm chart for the sealed-secrets controller.
type: application

dependencies:
  - name: sealed-secrets
    version: 2.18.1
    repository: https://bitnami-labs.github.io/sealed-secrets