apiVersion: v2
name: cert-manager
description: A Helm chart for cert-manager
type: application
version: 1.20.0

dependencies:
  - name: cert-manager
    version: v1.19.3
    repository: https://charts.jetstack.io
  - name: cert-manager-issuer
    version: 0.0.*
    repository: https://moreirodamian.github.io/helm-charts/
